; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+m,+xcvalu -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; This file tests that generic C idioms are automatically lowered to XCValu
; instructions without requiring explicit builtin/intrinsic calls.

;===----------------------------------------------------------------------===;
; XCValu — add/sub with normalisation shift from plain C
;===----------------------------------------------------------------------===;

; (a + b) >> 3 (arithmetic right shift, constant)  →  cv.addn
define i32 @test_addn(i32 %a, i32 %b) {
; CHECK-LABEL: test_addn:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.addn a0, a0, a1, 3
; CHECK-NEXT:    ret
  %add = add i32 %a, %b
  %res = ashr i32 %add, 3
  ret i32 %res
}

; (unsigned)(a + b) >> 4 (logical right shift, constant)  →  cv.addun
define i32 @test_addun(i32 %a, i32 %b) {
; CHECK-LABEL: test_addun:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.addun a0, a0, a1, 4
; CHECK-NEXT:    ret
  %add = add i32 %a, %b
  %res = lshr i32 %add, 4
  ret i32 %res
}

; (a - b) >> 2 (arithmetic)  →  cv.subn
define i32 @test_subn(i32 %a, i32 %b) {
; CHECK-LABEL: test_subn:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subn a0, a0, a1, 2
; CHECK-NEXT:    ret
  %sub = sub i32 %a, %b
  %res = ashr i32 %sub, 2
  ret i32 %res
}

; (unsigned)(a - b) >> 1 (logical)  →  cv.subun
define i32 @test_subun(i32 %a, i32 %b) {
; CHECK-LABEL: test_subun:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subun a0, a0, a1, 1
; CHECK-NEXT:    ret
  %sub = sub i32 %a, %b
  %res = lshr i32 %sub, 1
  ret i32 %res
}

; Edge case: shift by 0 is optimized away before ISel, so only a plain add remains
define i32 @test_addn_shift0(i32 %a, i32 %b) {
; CHECK-LABEL: test_addn_shift0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %add = add i32 %a, %b
  %res = ashr i32 %add, 0
  ret i32 %res
}

; Edge case: shift by 31 (maximum uimm5)
define i32 @test_addn_shift31(i32 %a, i32 %b) {
; CHECK-LABEL: test_addn_shift31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.addn a0, a0, a1, 31
; CHECK-NEXT:    ret
  %add = add i32 %a, %b
  %res = ashr i32 %add, 31
  ret i32 %res
}

; (a + b) >> reg (arithmetic, register shift)  →  cv.addnr
define i32 @test_addnr(i32 %a, i32 %b, i32 %shift) {
; CHECK-LABEL: test_addnr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.addnr a0, a1, a2
; CHECK-NEXT:    ret
  %add = add i32 %a, %b
  %res = ashr i32 %add, %shift
  ret i32 %res
}

; (a + b) >> reg (logical, register shift)  →  cv.addunr
define i32 @test_addunr(i32 %a, i32 %b, i32 %shift) {
; CHECK-LABEL: test_addunr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.addunr a0, a1, a2
; CHECK-NEXT:    ret
  %add = add i32 %a, %b
  %res = lshr i32 %add, %shift
  ret i32 %res
}

; (a - b) >> reg (arithmetic)  →  cv.subnr
define i32 @test_subnr(i32 %a, i32 %b, i32 %shift) {
; CHECK-LABEL: test_subnr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subnr a0, a1, a2
; CHECK-NEXT:    ret
  %sub = sub i32 %a, %b
  %res = ashr i32 %sub, %shift
  ret i32 %res
}

; (a - b) >> reg (logical)  →  cv.subunr
define i32 @test_subunr(i32 %a, i32 %b, i32 %shift) {
; CHECK-LABEL: test_subunr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subunr a0, a1, a2
; CHECK-NEXT:    ret
  %sub = sub i32 %a, %b
  %res = lshr i32 %sub, %shift
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; Realistic DSP-style examples
;===----------------------------------------------------------------------===;

; Fixed-point average: (a + b) >> 1  →  cv.addn
define i32 @test_fixed_point_avg(i32 %a, i32 %b) {
; CHECK-LABEL: test_fixed_point_avg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.addn a0, a0, a1, 1
; CHECK-NEXT:    ret
  %sum = add i32 %a, %b
  %avg = ashr i32 %sum, 1
  ret i32 %avg
}
