; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+m,+xcvmac -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; This file tests that generic C idioms are automatically lowered to XCVmac
; instructions without requiring explicit builtin/intrinsic calls.

;===----------------------------------------------------------------------===;
; XCVmac — multiply-accumulate from plain C
;===----------------------------------------------------------------------===;

; acc += a * b  →  cv.mac
define i32 @test_mac(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_mac:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.mac a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %mul = mul i32 %a, %b
  %res = add i32 %acc, %mul
  ret i32 %res
}

; acc += a * b (commuted add operands — should still match)
define i32 @test_mac_commuted(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_mac_commuted:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.mac a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %mul = mul i32 %a, %b
  %res = add i32 %mul, %acc
  ret i32 %res
}

; acc -= a * b  →  cv.msu
define i32 @test_msu(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_msu:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.msu a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %mul = mul i32 %a, %b
  %res = sub i32 %acc, %mul
  ret i32 %res
}

; Loop-based MAC: sum += arr[i] * coeffs[i]
; This tests that the compiler uses cv.mac in a realistic loop
define i32 @test_mac_loop(ptr %arr, ptr %coeffs, i32 %n) {
; CHECK-LABEL: test_mac_loop:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a3, 0
; CHECK-NEXT:    blez a2, .LBB3_2
; CHECK-NEXT:  .LBB3_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    lw a4, 0(a0)
; CHECK-NEXT:    lw a5, 0(a1)
; CHECK-NEXT:    addi a2, a2, -1
; CHECK-NEXT:    addi a1, a1, 4
; CHECK-NEXT:    cv.mac a3, a4, a5
; CHECK-NEXT:    addi a0, a0, 4
; CHECK-NEXT:    bnez a2, .LBB3_1
; CHECK-NEXT:  .LBB3_2: # %exit
; CHECK-NEXT:    mv a0, a3
; CHECK-NEXT:    ret
  %cmp = icmp sgt i32 %n, 0
  br i1 %cmp, label %loop, label %exit

loop:
  %i = phi i32 [ 0, %0 ], [ %i.next, %loop ]
  %sum = phi i32 [ 0, %0 ], [ %sum.next, %loop ]
  %ptr.a = getelementptr i32, ptr %arr, i32 %i
  %ptr.c = getelementptr i32, ptr %coeffs, i32 %i
  %a = load i32, ptr %ptr.a
  %c = load i32, ptr %ptr.c
  %mul = mul i32 %a, %c
  %sum.next = add i32 %sum, %mul
  %i.next = add i32 %i, 1
  %done = icmp eq i32 %i.next, %n
  br i1 %done, label %exit, label %loop

exit:
  %result = phi i32 [ 0, %0 ], [ %sum.next, %loop ]
  ret i32 %result
}

;===----------------------------------------------------------------------===;
; Realistic DSP-style examples
;===----------------------------------------------------------------------===;

; FIR filter tap: acc += coeff * sample, then normalise
; This should use cv.mac for the accumulate
define i32 @test_fir_tap(i32 %acc, i32 %coeff, i32 %sample) {
; CHECK-LABEL: test_fir_tap:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.mac a0, a1, a2
; CHECK-NEXT:    ret
  %mul = mul i32 %coeff, %sample
  %sum = add i32 %acc, %mul
  ret i32 %sum
}
