; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 -mattr=+m,+xcvmac -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; mul result has TWO uses: one in the add, one in a separate compare.
; cv.mac would clobber the multiplication result -> we MUST emit mul + add.
define i32 @test_mac_no_oneuse(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_mac_no_oneuse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    mul a0, a0, a1
; CHECK-NEXT:    sgtz a1, a0
; CHECK-NEXT:    neg a1, a1
; CHECK-NEXT:    and a1, a1, a2
; CHECK-NEXT:    add a0, a0, a1
; CHECK-NEXT:    ret
  %mul = mul i32 %a, %b
  %sum = add i32 %acc, %mul
  %ok  = icmp sgt i32 %mul, 0
  %sel = select i1 %ok, i32 %sum, i32 %mul
  ret i32 %sel
}
