; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+m,+xcvsimd -verify-machineinstrs < %s \
; RUN:   | FileCheck %s

; This file tests that all XCVsimd LLVM IR intrinsics are correctly lowered
; to their corresponding CV32E40P machine instructions.

;===----------------------------------------------------------------------===;
; ADD / SUB
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_add_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_add_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.add.h(i32 %a, i32 %b, i32 0)
  ret i32 %res
}

define i32 @test_cv_simd_add_h_div2(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_add_h_div2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.div2 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.add.h(i32 %a, i32 %b, i32 1)
  ret i32 %res
}

define i32 @test_cv_simd_add_h_div4(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_add_h_div4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.div4 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.add.h(i32 %a, i32 %b, i32 2)
  ret i32 %res
}

define i32 @test_cv_simd_add_h_div8(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_add_h_div8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.div8 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.add.h(i32 %a, i32 %b, i32 3)
  ret i32 %res
}

define i32 @test_cv_simd_add_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_add_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.add.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_add_sc_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_add_sc_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.add.sc.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_add_sc_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_add_sc_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.add.sc.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.add.sc.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_sub_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sub_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sub.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sub.h(i32 %a, i32 %b, i32 0)
  ret i32 %res
}

define i32 @test_cv_simd_sub_h_div2(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sub_h_div2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sub.div2 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sub.h(i32 %a, i32 %b, i32 1)
  ret i32 %res
}

define i32 @test_cv_simd_sub_h_div4(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sub_h_div4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sub.div4 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sub.h(i32 %a, i32 %b, i32 2)
  ret i32 %res
}

define i32 @test_cv_simd_sub_h_div8(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sub_h_div8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sub.div8 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sub.h(i32 %a, i32 %b, i32 3)
  ret i32 %res
}

define i32 @test_cv_simd_sub_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sub_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sub.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sub.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_sub_sc_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sub_sc_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sub.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sub.sc.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_sub_sc_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sub_sc_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sub.sc.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sub.sc.b(i32 %a, i32 %b)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; AVG / AVGU
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_avg_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avg_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avg.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avg.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_avg_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avg_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avg.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avg.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_avg_sc_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avg_sc_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avg.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avg.sc.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_avg_sc_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avg_sc_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avg.sc.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avg.sc.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_avgu_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avgu_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avgu.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avgu.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_avgu_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avgu_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avgu.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avgu.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_avgu_sc_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avgu_sc_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avgu.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avgu.sc.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_avgu_sc_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_avgu_sc_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.avgu.sc.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.avgu.sc.b(i32 %a, i32 %b)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; MIN / MINU / MAX / MAXU (representative: _h and _sc_b for each)
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_min_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_min_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.min.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.min.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_min_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_min_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.min.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.min.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_min_sc_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_min_sc_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.min.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.min.sc.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_min_sc_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_min_sc_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.min.sc.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.min.sc.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_minu_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_minu_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.minu.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.minu.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_minu_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_minu_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.minu.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.minu.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_max_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_max_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.max.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.max.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_max_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_max_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.max.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.max.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_maxu_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_maxu_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.maxu.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.maxu.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_maxu_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_maxu_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.maxu.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.maxu.b(i32 %a, i32 %b)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; SRL / SRA / SLL
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_srl_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_srl_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.srl.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.srl.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_srl_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_srl_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.srl.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.srl.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_srl_sc_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_srl_sc_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.srl.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.srl.sc.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_srl_sc_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_srl_sc_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.srl.sc.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.srl.sc.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_sra_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sra_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sra.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sra.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_sra_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sra_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sra.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sra.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_sll_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sll_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sll.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sll.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_sll_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_sll_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sll.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sll.b(i32 %a, i32 %b)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; OR / XOR / AND
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_or_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_or_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.or.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.or.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_or_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_or_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.or.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.or.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_xor_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_xor_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.xor.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.xor.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_xor_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_xor_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.xor.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.xor.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_and_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_and_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.and.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.and.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_and_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_and_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.and.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.and.b(i32 %a, i32 %b)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; ABS
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_abs_h(i32 %a) {
; CHECK-LABEL: test_cv_simd_abs_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.abs.h a0, a0
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.abs.h(i32 %a)
  ret i32 %res
}

define i32 @test_cv_simd_abs_b(i32 %a) {
; CHECK-LABEL: test_cv_simd_abs_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.abs.b a0, a0
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.abs.b(i32 %a)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; DOT PRODUCTS (non-accumulating)
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_dotup_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_dotup_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.dotup.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.dotup.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_dotup_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_dotup_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.dotup.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.dotup.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_dotup_sc_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_dotup_sc_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.dotup.sc.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.dotup.sc.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_dotup_sc_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_dotup_sc_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.dotup.sc.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.dotup.sc.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_dotusp_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_dotusp_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.dotusp.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.dotusp.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_dotsp_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_dotsp_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.dotsp.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.dotsp.h(i32 %a, i32 %b)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; SDOT (accumulating dot products)
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_sdotup_h(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_cv_simd_sdotup_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sdotup.h a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sdotup.h(i32 %a, i32 %b, i32 %acc)
  ret i32 %res
}

define i32 @test_cv_simd_sdotup_b(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_cv_simd_sdotup_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sdotup.b a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sdotup.b(i32 %a, i32 %b, i32 %acc)
  ret i32 %res
}

define i32 @test_cv_simd_sdotusp_h(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_cv_simd_sdotusp_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sdotusp.h a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sdotusp.h(i32 %a, i32 %b, i32 %acc)
  ret i32 %res
}

define i32 @test_cv_simd_sdotsp_h(i32 %a, i32 %b, i32 %acc) {
; CHECK-LABEL: test_cv_simd_sdotsp_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.sdotsp.h a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.sdotsp.h(i32 %a, i32 %b, i32 %acc)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; EXTRACT / EXTRACTU / INSERT
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_extract_h(i32 %a) {
; CHECK-LABEL: test_cv_simd_extract_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extract.h a0, a0, 1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.extract.h(i32 %a, i32 1)
  ret i32 %res
}

define i32 @test_cv_simd_extract_b(i32 %a) {
; CHECK-LABEL: test_cv_simd_extract_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extract.b a0, a0, 3
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.extract.b(i32 %a, i32 3)
  ret i32 %res
}

define i32 @test_cv_simd_extractu_h(i32 %a) {
; CHECK-LABEL: test_cv_simd_extractu_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extractu.h a0, a0, 0
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.extractu.h(i32 %a, i32 0)
  ret i32 %res
}

define i32 @test_cv_simd_extractu_b(i32 %a) {
; CHECK-LABEL: test_cv_simd_extractu_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.extractu.b a0, a0, 2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.extractu.b(i32 %a, i32 2)
  ret i32 %res
}

define i32 @test_cv_simd_insert_h(i32 %rd, i32 %rs1) {
; CHECK-LABEL: test_cv_simd_insert_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert.h a0, a1, 1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.insert.h(i32 %rd, i32 %rs1, i32 1)
  ret i32 %res
}

define i32 @test_cv_simd_insert_b(i32 %rd, i32 %rs1) {
; CHECK-LABEL: test_cv_simd_insert_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.insert.b a0, a1, 2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.insert.b(i32 %rd, i32 %rs1, i32 2)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; SHUFFLE / SHUFFLE2
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_shuffle_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_shuffle_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shuffle.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_shuffle_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_shuffle_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shuffle.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_shuffle_sci_h(i32 %a) {
; CHECK-LABEL: test_cv_simd_shuffle_sci_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shuffle.sci.h a0, a0, 2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle.sci.h(i32 %a, i32 2)
  ret i32 %res
}

; Test shuffle_sci_b pseudo expansion: imm=0x45 → bits[7:6]=1 → shufflei1
define i32 @test_cv_simd_shuffle_sci_b_i1(i32 %a) {
; CHECK-LABEL: test_cv_simd_shuffle_sci_b_i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shufflei1.sci.b a0, a0, 5
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle.sci.b(i32 %a, i32 69)
  ret i32 %res
}

; Test shuffle_sci_b pseudo expansion: imm=0x03 → bits[7:6]=0 → shufflei0
define i32 @test_cv_simd_shuffle_sci_b_i0(i32 %a) {
; CHECK-LABEL: test_cv_simd_shuffle_sci_b_i0:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shufflei0.sci.b a0, a0, 3
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle.sci.b(i32 %a, i32 3)
  ret i32 %res
}

; Test shuffle_sci_b pseudo expansion: imm=0x83 → bits[7:6]=2 → shufflei2
define i32 @test_cv_simd_shuffle_sci_b_i2(i32 %a) {
; CHECK-LABEL: test_cv_simd_shuffle_sci_b_i2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shufflei2.sci.b a0, a0, 3
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle.sci.b(i32 %a, i32 131)
  ret i32 %res
}

; Test shuffle_sci_b pseudo expansion: imm=0xC0 → bits[7:6]=3 → shufflei3
define i32 @test_cv_simd_shuffle_sci_b_i3(i32 %a) {
; CHECK-LABEL: test_cv_simd_shuffle_sci_b_i3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shufflei3.sci.b a0, a0, 0
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle.sci.b(i32 %a, i32 192)
  ret i32 %res
}

define i32 @test_cv_simd_shuffle2_h(i32 %rd, i32 %rs1, i32 %rs2) {
; CHECK-LABEL: test_cv_simd_shuffle2_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shuffle2.h a0, a1, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle2.h(i32 %rs1, i32 %rs2, i32 %rd)
  ret i32 %res
}

define i32 @test_cv_simd_shuffle2_b(i32 %rd, i32 %rs1, i32 %rs2) {
; CHECK-LABEL: test_cv_simd_shuffle2_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.shuffle2.b a0, a1, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.shuffle2.b(i32 %rs1, i32 %rs2, i32 %rd)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; PACK
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_packlo_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_packlo_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.pack a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.packlo.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_packhi_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_packhi_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.pack.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.packhi.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_packhi_b(i32 %rd, i32 %rs1, i32 %rs2) {
; CHECK-LABEL: test_cv_simd_packhi_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.packhi.b a0, a1, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.packhi.b(i32 %rd, i32 %rs1, i32 %rs2)
  ret i32 %res
}

define i32 @test_cv_simd_packlo_b(i32 %rd, i32 %rs1, i32 %rs2) {
; CHECK-LABEL: test_cv_simd_packlo_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.packlo.b a0, a1, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.packlo.b(i32 %rd, i32 %rs1, i32 %rs2)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; COMPARE (representative subset)
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_cmpeq_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpeq_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpeq.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpeq.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpeq_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpeq_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpeq.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpeq.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpne_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpne_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpne.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpne.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpgt_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpgt_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpgt.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpgt.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpge_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpge_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpge.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpge.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmplt_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmplt_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmplt.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmplt.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmple_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmple_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmple.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmple.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpgtu_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpgtu_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpgtu.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpgtu.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpgeu_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpgeu_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpgeu.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpgeu.b(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpltu_h(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpltu_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpltu.h a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpltu.h(i32 %a, i32 %b)
  ret i32 %res
}

define i32 @test_cv_simd_cmpleu_b(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_cmpleu_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cmpleu.b a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cmpleu.b(i32 %a, i32 %b)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; COMPLEX: cplxmul / cplxconj / subrotmj
;===----------------------------------------------------------------------===;

define i32 @test_cv_simd_cplxmul_r(i32 %rs1, i32 %rs2, i32 %rd) {
; CHECK-LABEL: test_cv_simd_cplxmul_r:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cplxmul.r a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cplxmul.r(i32 %rs1, i32 %rs2, i32 %rd, i32 0)
  ret i32 %res
}

define i32 @test_cv_simd_cplxmul_r_div2(i32 %rs1, i32 %rs2, i32 %rd) {
; CHECK-LABEL: test_cv_simd_cplxmul_r_div2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cplxmul.r.div2 a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cplxmul.r(i32 %rs1, i32 %rs2, i32 %rd, i32 1)
  ret i32 %res
}

define i32 @test_cv_simd_cplxmul_i(i32 %rs1, i32 %rs2, i32 %rd) {
; CHECK-LABEL: test_cv_simd_cplxmul_i:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cplxmul.i a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cplxmul.i(i32 %rs1, i32 %rs2, i32 %rd, i32 0)
  ret i32 %res
}

define i32 @test_cv_simd_cplxmul_i_div4(i32 %rs1, i32 %rs2, i32 %rd) {
; CHECK-LABEL: test_cv_simd_cplxmul_i_div4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cplxmul.i.div4 a2, a0, a1
; CHECK-NEXT:    mv a0, a2
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cplxmul.i(i32 %rs1, i32 %rs2, i32 %rd, i32 2)
  ret i32 %res
}

define i32 @test_cv_simd_cplxconj(i32 %a) {
; CHECK-LABEL: test_cv_simd_cplxconj:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.cplxconj a0, a0
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.cplxconj(i32 %a)
  ret i32 %res
}

define i32 @test_cv_simd_subrotmj(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_subrotmj:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subrotmj a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.subrotmj(i32 %a, i32 %b, i32 0)
  ret i32 %res
}

define i32 @test_cv_simd_subrotmj_div2(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_subrotmj_div2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subrotmj.div2 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.subrotmj(i32 %a, i32 %b, i32 1)
  ret i32 %res
}

define i32 @test_cv_simd_subrotmj_div4(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_subrotmj_div4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subrotmj.div4 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.subrotmj(i32 %a, i32 %b, i32 2)
  ret i32 %res
}

define i32 @test_cv_simd_subrotmj_div8(i32 %a, i32 %b) {
; CHECK-LABEL: test_cv_simd_subrotmj_div8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cv.subrotmj.div8 a0, a0, a1
; CHECK-NEXT:    ret
  %res = call i32 @llvm.riscv.cv.simd.subrotmj(i32 %a, i32 %b, i32 3)
  ret i32 %res
}

;===----------------------------------------------------------------------===;
; Intrinsic declarations
;===----------------------------------------------------------------------===;

; ADD/SUB
declare i32 @llvm.riscv.cv.simd.add.h(i32, i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.add.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.add.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.add.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.sub.h(i32, i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.sub.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.sub.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.sub.sc.b(i32, i32)

; AVG/AVGU
declare i32 @llvm.riscv.cv.simd.avg.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.avg.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.avg.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.avg.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.avgu.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.avgu.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.avgu.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.avgu.sc.b(i32, i32)

; MIN/MINU/MAX/MAXU
declare i32 @llvm.riscv.cv.simd.min.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.min.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.min.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.min.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.minu.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.minu.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.minu.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.minu.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.max.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.max.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.max.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.max.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.maxu.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.maxu.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.maxu.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.maxu.sc.b(i32, i32)

; SRL/SRA/SLL
declare i32 @llvm.riscv.cv.simd.srl.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.srl.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.srl.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.srl.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.sra.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.sra.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.sra.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.sra.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.sll.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.sll.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.sll.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.sll.sc.b(i32, i32)

; OR/XOR/AND
declare i32 @llvm.riscv.cv.simd.or.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.or.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.or.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.or.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.xor.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.xor.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.xor.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.xor.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.and.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.and.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.and.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.and.sc.b(i32, i32)

; ABS
declare i32 @llvm.riscv.cv.simd.abs.h(i32)
declare i32 @llvm.riscv.cv.simd.abs.b(i32)

; DOT (non-accumulating)
declare i32 @llvm.riscv.cv.simd.dotup.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotup.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotup.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotup.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotusp.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotusp.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotusp.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotusp.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotsp.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotsp.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotsp.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.dotsp.sc.b(i32, i32)

; SDOT (accumulating)
declare i32 @llvm.riscv.cv.simd.sdotup.h(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotup.b(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotup.sc.h(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotup.sc.b(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotusp.h(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotusp.b(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotusp.sc.h(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotusp.sc.b(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotsp.h(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotsp.b(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotsp.sc.h(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.sdotsp.sc.b(i32, i32, i32)

; EXTRACT/EXTRACTU/INSERT
declare i32 @llvm.riscv.cv.simd.extract.h(i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.extract.b(i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.extractu.h(i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.extractu.b(i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.insert.h(i32, i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.insert.b(i32, i32, i32 immarg)

; SHUFFLE
declare i32 @llvm.riscv.cv.simd.shuffle.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.shuffle.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.shuffle.sci.h(i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.shuffle.sci.b(i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.shuffle2.h(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.shuffle2.b(i32, i32, i32)

; PACK
declare i32 @llvm.riscv.cv.simd.packlo.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.packhi.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.packhi.b(i32, i32, i32)
declare i32 @llvm.riscv.cv.simd.packlo.b(i32, i32, i32)

; COMPARE
declare i32 @llvm.riscv.cv.simd.cmpeq.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpeq.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpeq.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpeq.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpne.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpne.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpne.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpne.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgt.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgt.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgt.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgt.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpge.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpge.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpge.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpge.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmplt.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmplt.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmplt.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmplt.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmple.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmple.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmple.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmple.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgtu.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgtu.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgtu.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgtu.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgeu.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgeu.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgeu.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpgeu.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpltu.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpltu.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpltu.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpltu.sc.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpleu.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpleu.b(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpleu.sc.h(i32, i32)
declare i32 @llvm.riscv.cv.simd.cmpleu.sc.b(i32, i32)

; COMPLEX
declare i32 @llvm.riscv.cv.simd.cplxmul.r(i32, i32, i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.cplxmul.i(i32, i32, i32, i32 immarg)
declare i32 @llvm.riscv.cv.simd.cplxconj(i32)
declare i32 @llvm.riscv.cv.simd.subrotmj(i32, i32, i32 immarg)
